/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;

class DishStackTest {
    @Test
    void testPushIncreasesSize() {
        DishStack stack = new DishStack();

        stack.push(new Dish("Dish 1"));
        stack.push(new Dish("Dish 2"));

        assertEquals(2, stack.size());
    }

    @Test
    void testPeek() {
        DishStack stack = new DishStack();

        stack.push(new Dish("Bottom"));
        stack.push(new Dish("Top"));

        assertEquals("Top", stack.peek().description);
        assertEquals(2, stack.size()); // Peek shouldn't remove the item
    }

    @Test
    void testPop() {
        DishStack stack = new DishStack();

        stack.push(new Dish("First"));
        stack.push(new Dish("Second"));

        Dish removed = stack.pop();

        assertEquals("Second", removed.description);
        assertEquals(1, stack.size());
    }

    @Test
    void testPushWhenFull() {
        DishStack stack = new DishStack(2);

        stack.push(new Dish("One"));
        stack.push(new Dish("Two"));
        stack.push(new Dish("Three"));

        assertEquals(2, stack.size());
    }

    @Test
    void testClear() {
        DishStack stack = new DishStack();

        stack.push(new Dish("One"));
        stack.push(new Dish("Two"));

        stack.clear();

        assertEquals(0, stack.size());
        assertNull(stack.peek());
    }
}
